WARNING 2018-08-14 11:08:24,899 /home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py 170: Not Found: /
WARNING 2018-08-14 11:08:25,006 /home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py 170: Not Found: /favicon.ico
WARNING 2018-08-14 11:08:45,039 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1036: 用户缺乏隶属信息
WARNING 2018-08-14 11:08:45,052 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1050: (1146, "Table 'hellocial.user_logs' doesn't exist")
WARNING 2018-08-14 11:25:05,015 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1036: 用户缺乏隶属信息
WARNING 2018-08-14 11:25:05,016 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1050: (1146, "Table 'hellocial.user_logs' doesn't exist")
WARNING 2018-08-14 11:28:35,997 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1036: 用户缺乏隶属信息
WARNING 2018-08-14 11:28:35,998 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1050: (1146, "Table 'hellocial.user_logs' doesn't exist")
WARNING 2018-08-14 11:29:51,601 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1036: 用户缺乏隶属信息
WARNING 2018-08-14 11:29:51,602 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1050: (1146, "Table 'hellocial.user_logs' doesn't exist")
WARNING 2018-08-14 11:33:49,949 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1036: 用户缺乏隶属信息
WARNING 2018-08-14 11:33:49,962 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1050: (1146, "Table 'hellocial.user_logs' doesn't exist")
WARNING 2018-08-14 11:41:49,343 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1036: 用户缺乏隶属信息
WARNING 2018-08-14 11:41:49,345 /home/python/Desktop/Hellocial/Hellocial_0_1/apps/users/views.py 1050: (1146, "Table 'hellocial.user_logs' doesn't exist")
WARNING 2018-08-14 11:49:49,975 /home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py 170: Not Found: /users/auser_fornum
WARNING 2018-08-14 11:50:06,644 /home/python/.virtualenvs/dailyfresh/local/lib/python3.5/site-packages/django/core/handlers/base.py 170: Not Found: /ascript/fornum
